<a href="https://colab.research.google.com/github/Karuna9502/PYTHON_DAILY_PRACTICE/blob/main/numpy_practice/DAY1_NUMPY_ARRAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CREATE AN EMPTY AND FULL NUMPY ARRAY**

In [ ]:
import numpy as np

**AS WE KNOW NUMPY HAVE IN-BULIT FUNCTION np.empty() and np.full()**




**I USE THESE FUNCTION TO SOLVE THIS PROBLEM**

In [ ]:
empty_array = np.empty((3,4))
print(empty_array)

[[1.69470136e-313 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


In [ ]:
full_array = np.full((3,4), 3)
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
empty1_array = np.empty(5)
print(empty1_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
full1_array = np.full((3),5)
print(full1_array)

[5 5 5]
