<a href="https://colab.research.google.com/github/Karuna9502/PYTHON_DAILY_PRACTICE/blob/main/numpy_practice/DAY2_NUMPY_ARRAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create a Numpy array filled with all zeros - Python**

In [1]:
import numpy as np

In [2]:
#IN 1D ARRAY
arr_1d = np.zeros(5)
print(arr_1d)


#np.zeros(5) function creates a 1D array with 5 elements, all initialized to 0.
#By default, the data type of the array is float, so the zeros are represented as 0.0.

[0. 0. 0. 0. 0.]


****

In [3]:
#IN 2D
arr_2d = np.zeros((3,3))
print(arr_2d)

#np.zeros((3, 4)) function creates a 2D array with 3 rows and 4 columns.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**numpy.zeros(shape, dtype=float)**

In [4]:
arr_2dd = np.zeros((3,2), dtype=int)
print(arr_2dd)
#HERE ELEMENTS ARE INTEGER TYPR

[[0 0]
 [0 0]
 [0 0]]


**By default, NumPy arrays are stored in row-major order (C order). However, specifying order='F' changes this to column-major order (Fortran-style).**



In [11]:
arr_row = np.zeros((3,4), dtype=int, order='C')
print(arr_row)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
arr_column = np.zeros((3,2),dtype = float, order = 'F')
print(arr_column)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
