<a href="https://colab.research.google.com/github/Karuna9502/PYTHON_DAILY_PRACTICE/blob/main/numpy_practice/DAY3_NUMPY_ARRAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy - Create array filled with all ones**


In [1]:
import numpy as np
# To create an array filled with all ones in Python, NumPy provides the
# numpy.ones() function. You can specify the shape and data type of the array.


**PARAMETER**


In [ ]:
# shape (int or tuple): Defines size of array.
# dtype (optional): Sets data type of elements.
# order (optional): Memory layout, 'C' -> Row-wise (default, C-style) and 'F' -> Column-wise (Fortran-style).


In [4]:
arr_1d = np.ones(2)
print(arr_1d)

[1. 1.]


In [6]:
arr_2d = np.ones((2,4))
print(arr_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arr_3d = np.ones((3,2,4), dtype = np.double)
print(arr_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
arr_datatype = np.ones((2,8), dtype = int)
print(arr_datatype)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [9]:
arr_column = np.ones((9,5),dtype = bool, order = 'F')
print(arr_column)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
